sudo: required
language: python

env:
  global:
    - DOCKER_IMAGE=alectolytic/rpmbuilder
    - OS_ARCH=x86_64
  matrix:
    - OS_TYPE=centos OS_DIST=epel OS_VERSION=7

services:
  - docker

install: true

before_install:
  - gem install package_cloud

script:
  - docker run -v ${PWD}:/sources -v ${PWD}:/output:Z -e "SRPM_ONLY=1" ${DOCKER_IMAGE}:${OS_TYPE}-${OS_VERSION}
  
after_success:  
  - package_cloud push getpagespeed/extras/el/7 *.src.rpm
