version: 2
jobs:
  build:
    machine: true
    steps:    
      - checkout
      - run:
          name: "Build all the .spec files via Docker image."
          command: docker run -v ${PWD}:/sources -v ${PWD}:/output:Z ${DOCKER_IMAGE}:${OS_TYPE}-${OS_VERSION} /bin/bash -c "rm -rf /etc/yum.repos.d/CentOS-Vault.repo; rm -rf /etc/yum.repos.d/CentOS-Sources.repo; sed -i 's/-v OUTPUT_UID/-z "${OUTPUT_UID}"/' /usr/bin/build; /usr/bin/build"
      - run:
          name: "Get rid of .src.rpm files."
          command: rm -rf *.src.rpm
      - run:
          name: "Check .rpm files."
          command: stat *.rpm
      - run:
          name: "Where am I"
          command: pwd
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project
  deploy:
    machine: true
    steps:
      - attach_workspace:
          at: /home/circleci 
      - run:
          name: "Delete stupid keys that was added by CircleCI by default"
          command: ssh-add -D              
      - add_ssh_keys:
          fingerprints:
            - "8c:a4:dd:2c:47:4c:63:aa:90:0b:e0:d6:15:be:87:82"      
      - run:
          name: "Delete stupid keys that was added by CircleCI by default"
          command: cat ~/.ssh/config
      - run:
          name: "Test contexts."
          command: echo $GPS_BUILD_USER
          context: getpagespeed-builder          
      - run:
          name: "Deploy all RPMs to GetPageSpeed repo."
          command: scp -r *.rpm $GPS_BUILD_USER@$GPS_BUILD_SERVER:$GPS_EXTRAS_EL7/x86_64/RPMS/
          context: getpagespeed-builder
      - run:
          name: "Sign the RPMs."
          command: ssh $GPS_BUILD_USER@$GPS_BUILD_SERVER "~/rpm-sign.exp $GPS_EXTRAS_EL7/x86_64/RPMS/*.rpm"
          context: getpagespeed-builder
      - run:
          name: "Recreate repo files."
          command: ssh $GPS_BUILD_USER@$GPS_BUILD_SERVER "createrepo -v --deltas --oldpackagedirs $GPS_EXTRAS_EL7/x86_64/ $GPS_EXTRAS_EL7/x86_64/"
          context: getpagespeed-builder  
      - run:
          name: "Generate repo view."
          command: ssh $GPS_BUILD_USER@$GPS_BUILD_SERVER "repoview $GPS_EXTRAS_EL7/x86_64/"
          context: getpagespeed-builder                    
workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
